# This file is generated by gyp; do not edit.

export builddir_name ?= /home/alex/chromium/android_official/src/base/out
.PHONY: all
all:
	$(MAKE) -C .. base_static xdg_mime symbolize xdg_mime base_static_win64 base_static symbolize base base check_example test_support_perf base_i18n test_support_base base_unittests
